// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjcnvqcbkamnwswmchve.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqY252cWNia2Ftbndzd21jaHZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY4MTMzNTIsImV4cCI6MjA4MjM4OTM1Mn0.6ooBjaCi0M8krCEAIs4FzKlF7b7EplmfrbKC-ldpEiI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
